[features]
seeds = true
[programs.localnet]
cpi_whirlpool = "29i4A6jkwKbWBquwpxCYwu67Dc7wqgBXARgQcA1mhT34"
liquidity_lockbox = "7ahQGWysExobjeZ91RTsNqTCN3kWyHGZ43ud2vB7VVoZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "artifacts/id.json"

[profile.release]
overflow-checks = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
